CREATE TABLE Administrator (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	login_id VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Organization (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
)ENGINE=InnoDB;

CREATE TABLE Field (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE,
	org_id INTEGER NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Analysis (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	field_id INTEGER NOT NULL
)ENGINE=InnoDB;